- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
    - id: check-added-large-files
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: detect-aws-credentials
    - id: detect-private-key
